import { DEFAULT_OG_IMAGE } from '@/data/site';

const OWN_IMAGE = /^\/(solutions|services|blog|case-studies)\/[^/]+$/;

/** Slug of the committed share image for a route, or null when it uses the default image. */
export const ogImageSlug = (path: string): string | null => {
  if (path === '/') return 'home';
  if (path === '/industries' || OWN_IMAGE.test(path)) return path.slice(1).replace(/\//g, '-');
  return null;
};

/** Site-relative path of a route's 1200x630 share image (generated by `npm run images`). */
export const ogImagePath = (path: string) => {
  const slug = ogImageSlug(path);
  return slug ? `/og/${slug}.jpg` : DEFAULT_OG_IMAGE;
};
